"""Check that the references inside a specification still resolve.

A specification points at itself constantly: it quotes the title of another
chapter, it links a UID, and it names a file. Every one of those goes stale
silently. StrictDoc only refuses to export a broken `[LINK:]`; a quoted chapter
title that nobody renamed alongside its heading, and a file name that moved,
both export cleanly and mislead the reader.

Four checks:

  1. a heading that was RENAMED, with --since <git revision>. A heading that
     existed at that revision, does not exist now, and is still quoted
     somewhere is a rename nobody followed through. This is exact, and it is
     the only one of the four that catches a heavy rewording - see 2.

  2. quoted chapter titles, by similarity. Most quoted text is ordinary prose,
     so flagging "this quote is not a heading" would drown the report; this
     reports a quote that is CLOSE to a real heading without matching one.
     It catches a light rewording and nothing else. Measured on md-basic-ja:
     a heavily reworded heading scores 0.69 against its stale references while
     ordinary prose reaches 0.71 against some heading, so no threshold
     separates the two. That is what --since is for.

  3. `[LINK: UID]` targets. StrictDoc already refuses to export a link to a UID
     that does not exist, so this only confirms it and counts. A link inside a
     code span is being shown, not made, and is skipped.

  4. file names written in inline code. Resolved against the specification
     folder, the repository root, and then the repository as a whole, because
     a guide names a file the way a reader says it rather than by full path.

Headings always come from the sources, never from the export: a JSON left over
from before a rename still carries the old heading, and reading titles from it
hid exactly the rename check 1 exists to find (measured).

Fenced blocks are dropped before any of this. A query body quotes and names
things it does not reference.

Exit code is 0 when every reference resolves, 1 otherwise.

Usage:
    python tools/check-references.py <specification folder> [--json <index.json>]
    python tools/check-references.py <specification folder> --export
    python tools/check-references.py <folder> --since HEAD
    python tools/check-references.py <folder> --list-headings
"""

import argparse
import difflib
import json
import pathlib
import re
import subprocess
import sys
import tempfile

# A quote has to be at least this long before a near-match means anything. Short
# quotes ("no", "figure") collide with headings by accident.
MIN_QUOTE = 6
# Similarity above which a quote is treated as a failed reference rather than
# ordinary prose. Measured on md-basic-en, which is the harder of the two
# because English words overlap where Japanese ones do not:
#
#   0.81  a real stale reference. "What to replace when you use this in another
#         project" against the heading "What to substitute when you use this
#         guide on another project" - found by this check, fixed since
#   0.72  the highest-scoring ordinary quote. A guide quotes the sentences that
#         dangle once a figure moves ("we put a small figure in the body"), and
#         those resemble the heading "Do not put large figures in the body"
#
# 0.78 sits between them. Raising it hides a rename that changed few words;
# lowering it reports prose. Re-measure rather than guess if this starts to
# report noise.
NEAR_MATCH = 0.78

FENCE = re.compile(r"^ {0,4}(`{3,})")
INLINE_CODE = re.compile(r"`[^`]+`")
# A Japanese guide quotes a heading in corner brackets. Building them from code
# points rather than writing them keeps this file ASCII (NFR-010).
JA_OPEN = chr(0x300C)
JA_CLOSE = chr(0x300D)
JA_QUOTE = re.compile("{0}([^{0}{1}]{{1,120}}){1}".format(JA_OPEN, JA_CLOSE))
EN_QUOTE = re.compile(r"\"([^\"\n]{1,120})\"")
LINK = re.compile(r"\[LINK:\s*([^\]]+)\]")
CODE_SPAN = re.compile(r"`([^`]+)`")

PATH_SUFFIXES = (".md", ".sdoc", ".sgra", ".py", ".csv", ".svg", ".tsv",
                 ".json", ".css", ".txt", ".sh", ".ps1", ".drawio", ".png")
# A path this script must not resolve, and why.
SKIP_PATH_PARTS = ("*", "?", "<", ">", "$", "%", "|", " ")
# Generated by an export, so absent from a clean checkout.
SKIP_PREFIXES = ("output/", "out/", "_static/")
# Written by an export rather than by hand.
GENERATED = frozenset(["index.json"])
# Names that are absent from this repository on purpose. A guide invents some of
# them to show a convention, and cites others as evidence from StrictDoc's own
# source. Reporting them would train a reader to ignore the report.
# The Japanese name is written as an escape so this file stays ASCII (NFR-010).
ABSENT_ON_PURPOSE = frozenset([
    "11-example.md",      # "the number after the highest one that exists"
    "90-defects.md",      # only inside the query fixture
    "FILE.md",
    "SPEC.txt",
    "patterns.sgra",      # the deleted sdoc-patterns sample, quoted as history
    "x.svg",              # the `![alt](_assets/x.svg)` syntax example
    # the same syntax example written in Japanese, built from code points so
    # this file stays ASCII
    "".join(chr(c) for c in (0x56F3, 0x306E, 0x540D, 0x524D)) + ".png",
    "path",               # the bare `![alt](path)` syntax example
    # StrictDoc's own source, cited for a measured behaviour. Upstream lives in
    # temp/strictdoc-main and is not tracked here.
    "reader.py",
    "markdown_to_html_fragment_writer.py",
])
# Folders that hold no reference target: build output and the upstream checkout.
INDEX_SKIP = ("output", "temp", ".git", "node_modules", "__pycache__", ".venv")
# `[LINK: UID]` is the guide showing the syntax, not linking anything.
LINK_PLACEHOLDERS = frozenset(["UID"])


def prose_lines(text):
    """Yield (line number, line) for the prose, dropping fenced blocks.

    The line number is the one in the source file, not the one in the stripped
    text. A report that points at the wrong line costs more than it saves.
    """
    open_len = 0
    for number, line in enumerate(text.splitlines(), 1):
        match = FENCE.match(line)
        if match:
            width = len(match.group(1))
            if open_len == 0:
                open_len = width
            elif width >= open_len:
                open_len = 0
            continue
        if open_len == 0:
            yield number, line


def strip_fences(text):
    """The prose alone, as one string."""
    return "\n".join(line for _, line in prose_lines(text))


def headings_of(index_path):
    """Every document title and section title in the project."""
    data = json.loads(pathlib.Path(index_path).read_text(encoding="utf-8"))
    found = set()
    uids = set()

    def walk(node):
        title = node.get("TITLE")
        if title:
            found.add(title.strip())
        uid = node.get("UID")
        if uid:
            uids.add(uid)
        for child in node.get("NODES") or []:
            walk(child)

    for document in data.get("DOCUMENTS") or []:
        walk(document)
    return found, uids


def markdown_headings(folder):
    """Headings taken from the sources, including any file StrictDoc skips."""
    found = set()
    root = pathlib.Path(folder)
    for path in sorted(list(root.rglob("*.md")) + list(root.rglob("*.sdoc"))):
        if "output" in path.parts:
            continue
        for line in strip_fences(path.read_text(encoding="utf-8")).splitlines():
            if line.startswith("#"):
                found.add(line.lstrip("#").strip())
            # An .sdoc names a section with a TITLE: field instead.
            elif line.strip().startswith("TITLE:"):
                found.add(line.split(":", 1)[1].strip())
    return found


def export(project, workdir):
    out = workdir / "export"
    done = subprocess.run(
        ["strictdoc", "export", str(project), "--formats=json",
         "--output-dir", str(out), "--no-parallelization"],
        capture_output=True, text=True, encoding="utf-8", errors="replace")
    if done.returncode != 0:
        sys.stderr.write(done.stdout)
        sys.stderr.write(done.stderr)
        raise SystemExit("strictdoc export failed for {0}".format(project))
    return out / "json" / "index.json"


def headings_at(revision, folder, root):
    """The headings this folder carried at a git revision, or None.

    Similarity cannot catch a heading that was reworded heavily: measured on
    md-basic-ja, a renamed heading scores 0.69 against its stale references
    while ordinary prose reaches 0.71 against some heading, so no threshold
    separates them. Git does separate them, exactly. A heading that existed at
    the revision, does not exist now, and is still quoted somewhere, is a
    rename whose references nobody followed.
    """
    listing = subprocess.run(
        ["git", "-C", str(root), "ls-tree", "-r", "--name-only", revision, "--",
         str(pathlib.Path(folder).as_posix())],
        capture_output=True, text=True, encoding="utf-8", errors="replace")
    if listing.returncode != 0:
        return None
    found = set()
    for name in listing.stdout.splitlines():
        if not name.endswith((".md", ".sdoc")):
            continue
        blob = subprocess.run(
            ["git", "-C", str(root), "show", "{0}:{1}".format(revision, name)],
            capture_output=True, text=True, encoding="utf-8", errors="replace")
        if blob.returncode != 0:
            continue
        for line in strip_fences(blob.stdout).splitlines():
            if line.startswith("#"):
                found.add(line.lstrip("#").strip())
            elif line.strip().startswith("TITLE:"):
                found.add(line.split(":", 1)[1].strip())
    return found


def repo_index(root):
    """Every file in the repository, by relative path and by bare name.

    A guide names a file the way a reader would say it - `audit.sh`, not
    `claude-skills/strictdoc-md/scripts/audit.sh` - and names a figure that
    lives in a sibling sample. Resolving only against the specification folder
    would report all of those, so the index carries the whole tree once.
    """
    paths = set()
    names = {}
    for path in pathlib.Path(root).rglob("*"):
        if not path.is_file():
            continue
        if any(part in INDEX_SKIP for part in path.parts):
            continue
        rel = path.relative_to(root).as_posix()
        paths.add(rel)
        names.setdefault(path.name, rel)
    return paths, names


def resolves(token, folder, root, paths, names):
    """True when a file named in the text can be found."""
    if (folder / token).exists() or (root / token).exists():
        return True
    if token in paths:
        return True
    # A relative path written from inside the skill, such as scripts/audit.sh.
    if "/" in token and any(p.endswith("/" + token) for p in paths):
        return True
    return pathlib.PurePosixPath(token).name in names


def looks_like_path(token):
    if any(part in token for part in SKIP_PATH_PARTS):
        return False
    if token.startswith(SKIP_PREFIXES):
        return False
    # A bare extension is the guide naming a format, not a file. `.md` and
    # `.sgra` appear constantly in prose and none of them is a path. Note that
    # PurePosixPath(".md").suffix is "" and its stem is ".md", so the name has
    # to be tested directly rather than through the suffix.
    name = pathlib.PurePosixPath(token).name
    if name.startswith("."):
        return False
    return token.endswith(PATH_SUFFIXES)


def normalise(text):
    """Put a quote and a heading into the same shape before comparing.

    A heading writes a code span with backticks and a reference to it usually
    does not, and a reference often carries the chapter number the heading
    itself does not hold. Neither difference means the reference is stale.
    """
    text = text.replace("`", "").strip()
    text = re.sub(r"^[0-9]+(\.[0-9]+)*\.?\s*", "", text)
    # A sentence lowercases a title it names mid-clause. Case is not a rename.
    return " ".join(text.split()).casefold()


def main():
    parser = argparse.ArgumentParser(
        description="Check that quoted headings, [LINK:] and file names resolve.")
    parser.add_argument("folder", help="the specification folder")
    parser.add_argument("--json", help="an existing index.json for that folder")
    parser.add_argument("--export", action="store_true",
                        help="export the folder to JSON first")
    parser.add_argument("--root", default=".",
                        help="repository root, for paths written from the top")
    parser.add_argument("--list-headings", action="store_true",
                        help="print every heading and exit")
    parser.add_argument("--since", default="",
                        help="a git revision. Report a heading that existed then, "
                             "is gone now, and is still quoted")
    parser.add_argument("--allow", default="",
                        help="comma separated file names this project names on "
                             "purpose without them existing")
    args = parser.parse_args()

    for stream in (sys.stdout, sys.stderr):
        stream.reconfigure(errors="replace")

    folder = pathlib.Path(args.folder)
    root = pathlib.Path(args.root)
    if not folder.is_dir():
        raise SystemExit("not a folder: {0}".format(folder))

    with tempfile.TemporaryDirectory(prefix="check-references-") as temp:
        workdir = pathlib.Path(temp)
        if args.export:
            index = export(folder, workdir)
        elif args.json:
            index = pathlib.Path(args.json)
        else:
            index = None
        _, uids = (headings_of(index) if index else (set(), set()))

    # Headings come from the sources, never from the export. A JSON left over
    # from before a rename still carries the old heading, and taking titles
    # from it hid exactly the rename this check exists to find (measured on a
    # deliberately broken copy).
    titles = markdown_headings(folder)
    normalised_titles = set(
        normalise(t) for t in titles if normalise(t))
    if args.list_headings:
        for title in sorted(titles):
            print(title)
        return 0

    renamed = []
    if args.since:
        was = headings_at(args.since, folder, root)
        if was is None:
            raise SystemExit("cannot read revision: " + args.since)
        gone = set(normalise(t) for t in was if normalise(t))
        gone -= normalised_titles
    else:
        gone = set()

    indexed_paths, indexed_names = repo_index(root)
    allowed = set(ABSENT_ON_PURPOSE)
    allowed.update(name.strip() for name in (args.allow or "").split(",")
                   if name.strip())

    stale_quotes = []
    broken_links = []
    missing_paths = []
    resolved = {"quote": 0, "link": 0, "path": 0}

    sources = sorted(list(folder.rglob("*.md")) + list(folder.rglob("*.sdoc")))
    for path in sources:
        if "output" in path.parts:
            continue
        raw = path.read_text(encoding="utf-8")
        prose = list(prose_lines(raw))
        rel = path.relative_to(folder).as_posix()

        # 3. file names, taken from inline code before it is stripped
        for line_no, line in prose:
            for token in CODE_SPAN.findall(line):
                token = token.strip()
                if not looks_like_path(token):
                    continue
                name = pathlib.PurePosixPath(token).name
                if name in allowed or name in GENERATED:
                    continue
                if resolves(token, folder, root, indexed_paths, indexed_names):
                    resolved["path"] += 1
                else:
                    missing_paths.append((rel, line_no, token))

        # 2. [LINK: UID]. A link inside a code span is being shown, not made:
        #    the guides write `[LINK: FIG-FLOW]` to teach the syntax, and
        #    StrictDoc does not resolve it either (measured - that document
        #    exports cleanly while FIG-FLOW is absent from the index).
        for line_no, line in prose:
            for target in LINK.findall(INLINE_CODE.sub(" ", line)):
                target = target.strip()
                if target in LINK_PLACEHOLDERS:
                    continue
                if not uids or target in uids:
                    resolved["link"] += 1
                else:
                    broken_links.append((rel, line_no, target))

        # 1. quoted headings
        for line_no, line in prose:
            for pattern in (JA_QUOTE, EN_QUOTE):
                for quote in pattern.findall(line):
                    quote = normalise(quote)
                    if len(quote) < MIN_QUOTE:
                        continue
                    # English double quotes wrap a single token constantly - a
                    # JSON value, a field name, a status such as "rolledback",
                    # which scores 89% against the heading "rollback". A chapter
                    # title is a phrase, so require a space. Japanese corner
                    # brackets need no such rule: a Japanese title carries no
                    # spaces either, and the brackets are not used for literals.
                    if pattern is EN_QUOTE and " " not in quote:
                        continue
                    # A reference may quote only part of a heading, and a
                    # heading may be quoted with its chapter number attached.
                    # Containment either way is a resolved reference.
                    if quote in gone:
                        renamed.append((rel, line_no, quote))
                        continue
                    if any(quote in title or title in quote
                           for title in normalised_titles):
                        resolved["quote"] += 1
                        continue
                    best, score = None, 0.0
                    for title in normalised_titles:
                        ratio = difflib.SequenceMatcher(
                            None, quote, title).ratio()
                        if ratio > score:
                            best, score = title, ratio
                    if score >= NEAR_MATCH:
                        stale_quotes.append((rel, line_no, quote, best, score))

    print("{0}\n".format(folder.as_posix()))
    print("  resolved   headings {0}   [LINK:] {1}   file names {2}".format(
        resolved["quote"], resolved["link"], resolved["path"]))

    problems = 0
    for name, rows in (("quote names a heading that was renamed", renamed),
                       ("quoted heading does not match any heading", stale_quotes),
                       ("[LINK:] target does not exist", broken_links),
                       ("file named in the text does not exist", missing_paths)):
        if not rows:
            print("  ok    {0:<44} 0".format(name))
            continue
        problems += 1
        print("  FAIL  {0:<44} {1}".format(name, len(rows)))
        for row in rows:
            if len(row) == 5:
                rel, line_no, quote, best, score = row
                print("          {0}:{1}  \"{2}\"".format(rel, line_no, quote))
                print("              closest heading ({0:.0%}): \"{1}\""
                      .format(score, best))
            else:
                rel, line_no, token = row
                print("          {0}:{1}  {2}".format(rel, line_no, token))

    print("\n" + "-" * 60)
    if problems:
        print("FAIL: {0} kind(s) of reference no longer resolve".format(problems))
        return 1
    print("PASS: every reference resolves")
    return 0


if __name__ == "__main__":
    sys.exit(main())
